// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using OutcastBot.Enumerations;
using OutcastBot.Ojects;
using System;

namespace OutcastBot.Migrations
{
    [DbContext(typeof(BuildContext))]
    partial class BuildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("OutcastBot.Ojects.Build", b =>
                {
                    b.Property<int>("BuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AuthorId");

                    b.Property<string>("BuildUrl");

                    b.Property<string>("Description");

                    b.Property<int>("DownVotes");

                    b.Property<bool>("ExpansionRequired");

                    b.Property<string>("ForumUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<int>("Mastery");

                    b.Property<ulong>("MessageId");

                    b.Property<string>("PatchVersion");

                    b.Property<string>("Title");

                    b.Property<int>("UpVotes");

                    b.Property<string>("VideoUrl");

                    b.HasKey("BuildId");

                    b.ToTable("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
